### ISSUE TITLE
Start Todo

### ISSUE THREAD

**Issue by henriquefons** [henriquefons/mini-project-vue#1]
_Todo_ da primeira semana
---

- [x] Iniciar o projeto com Vue CLI
- [x] Instalar Vuex e estruturar pastas
- [x] Instalar Axios e estruturar pastas
- [x] Adicionar API da https://gorest.co.in e configurar token de acesso
- [x] Adicionar o BootStrap 
- [x] Desenvolver tela inicial com Header para acessar outras paginas
- [x] Adicionar Vue Routes e estrutar links de acesso
- [x] Desenvolver tela de criar usuarios 
- [x] Desenvolver tela de listar usuarios com link para editar o usuario escolhido
- [x] Adaptar tela de criar usuários para poder edita-los tambem
- [x] Implementar validações da API para cadastrar e editar usuário
- [x] Desenvolver tela de listar postagens 
- [x] Armazenar dados usuários como login
- [x] Lógica para pegar dados do storage caso usuário esteja logado
- [x] Desenvolver página de mostrar postagens e seus comentários
- [x] Desenvolver listagem dos comentarios nos postings
- [x] Desenvolver tela de criar um post
- [x] Implementar criação de comentários
- [x] Usuarios logados podem filtrar pelos seus posts
- [x] Restrição para usuários ativos/inativos
- [x] Desenvolver pagina inicial
- [x] Consumir a API passando a paginação para as postagens (feito manualmente)
- [x] Verificar se o post tem comentários ou não
- [x] Implementar API do TODO e implementar página
- [x] Passar data para ficar legivel
- [x] Adicionar depedencias testes unitarios 
- [x] Fazer ao menos testes unitarios simples
- [ ] Testes unitarios complexos
- [ ] Passar a quantidade de posts retornados na paginação para 10
